name: Publish Docker image

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Build and publish image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Increase disk space available for building images
        run: |
          sudo rm -rf \
            /usr/share/dotnet \
            /usr/local/lib/android \
            /usr/local/.ghcup \
            /opt/ghc \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/local/share/powershell \
            /usr/share/swift \
            /usr/lib/jvm || true

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for the image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/enigma-pd-wml
          tags:
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
